import FluentKit
import Foundation

/// A recorded response from a person (and optionally an entity) to a specific question.
///
/// An `Answer` captures the value a respondent provided for a ``Question`` in the context
/// of a Navigator notation workflow. The value is stored as a JSON string to accommodate
/// the variety of question types (text, date, number, select, etc.).
///
/// The combination of `question_id`, `person_id`, and `value` must be unique — a person
/// cannot record the same answer to the same question twice.
///
/// ## Topics
///
/// ### Properties
///
/// - ``id``
/// - ``question``
/// - ``person``
/// - ``entity``
/// - ``value``
/// - ``insertedAt``
public final class Answer: Model, @unchecked Sendable {
    public static let schema = "answers"

    /// The unique identifier for this answer, generated by the database.
    @ID(key: .id)
    public var id: UUID?

    /// The question this answer responds to.
    @Parent(key: "question_id")
    public var question: Question

    /// The person who provided this answer.
    @Parent(key: "person_id")
    public var person: Person

    /// The entity on whose behalf this answer was provided, if applicable.
    @OptionalParent(key: "entity_id")
    public var entity: Entity?

    /// The recorded value for this answer, serialised as a JSON string.
    ///
    /// The format of the value depends on the associated ``Question``'s `questionType`.
    /// For example, a `yesNo` question stores `"true"` or `"false"`, while a `multiSelect`
    /// question stores a JSON array of strings.
    @Field(key: "value")
    public var value: String

    /// The timestamp when this answer was recorded.
    @Timestamp(key: "inserted_at", on: .create)
    public var insertedAt: Date?

    /// The timestamp when this answer was last updated. Equal to `insertedAt`
    /// for unmodified rows — Answers are conventionally append-only at the
    /// service layer, but the column is present so every table satisfies the
    /// `inserted_at` / `updated_at` schema invariant.
    @Timestamp(key: "updated_at", on: .update)
    public var updatedAt: Date?

    /// Creates a new empty `Answer` instance.
    public init() {}
}
