import FluentKit
import Foundation

/// A single inbound email received at one of the firm's `support@` addresses.
///
/// `EmailMessage` is the inbound side of the mailroom stack and is intentionally kept
/// separate from the physical ``Letter`` / ``Mailroom`` models. Each deployment runs a
/// single `support@<brand-domain>` mailbox, so the recipient (``toAddress``) alone
/// identifies which brand the mail belongs to — there is no parent ``Mailroom`` row.
///
/// The row stores both the parsed MIME envelope (for querying and display) and a
/// reference to the raw MIME source (``rawBlob``) for later forensic use. Attachments
/// are recorded as ``EmailAttachment`` rows, one per decoded MIME part.
///
/// ## Threading
///
/// The ``threadId`` field is denormalized at ingestion by walking the RFC 5322
/// `In-Reply-To` / `References` headers. This enables fast thread list queries
/// without touching the raw headers on every read. See `EmailThreadResolver`
/// in the ingestion service for the resolution algorithm.
public final class EmailMessage: Model, @unchecked Sendable {
    public static let schema = "email_messages"

    /// The unique identifier for this email, generated by the database.
    @ID(key: .id)
    public var id: UUID?

    /// The globally unique RFC 5322 `Message-ID` header value, including angle brackets.
    ///
    /// A uniqueness constraint on this column makes `POST /mail/inbound/ingest`
    /// idempotent — a duplicate delivery is resolved to the existing row rather
    /// than creating a second copy.
    @Field(key: "message_id")
    public var messageId: String

    /// The value of the RFC 5322 `In-Reply-To` header, if the message is a reply.
    @OptionalField(key: "in_reply_to")
    public var inReplyTo: String?

    /// The RFC 5322 `References` header parsed into an ordered list of ancestor
    /// `Message-ID` values (oldest first).
    ///
    /// Persisted as a JSONB document via ``JSONStored`` so Fluent encodes the
    /// array as one JSON value on both Postgres and SQLite. Access the list via
    /// `references.value`.
    @Field(key: "references")
    public var references: JSONStored<[String]>

    /// Denormalized thread identifier computed at ingestion.
    ///
    /// Equal to the ``messageId`` of the root message of the conversation. New
    /// threads use the current message's own ``messageId`` as the root.
    @Field(key: "thread_id")
    public var threadId: String

    /// The sender's email address, lower-cased and envelope-stripped.
    @Field(key: "from_address")
    public var fromAddress: String

    /// The sender's display name, if present in the `From` header.
    @OptionalField(key: "from_name")
    public var fromName: String?

    /// The support mailbox that received this email — e.g. `support@neonlaw.org`.
    ///
    /// Because each deployment runs one mailbox, this column alone identifies
    /// which brand the mail belongs to.
    @Field(key: "to_address")
    public var toAddress: String

    /// Addresses in the `Cc` header, if any. Stored as a JSONB document via
    /// ``JSONStored``. Access the list via `ccAddresses.value`.
    @Field(key: "cc_addresses")
    public var ccAddresses: JSONStored<[String]>

    /// Addresses in the `Bcc` header, if any. Rarely populated on inbound mail.
    /// Stored as a JSONB document via ``JSONStored``. Access via `bccAddresses.value`.
    @Field(key: "bcc_addresses")
    public var bccAddresses: JSONStored<[String]>

    /// The `Subject` header value. Stored verbatim — no normalization.
    @Field(key: "subject")
    public var subject: String

    /// The decoded `text/plain` part of the message body, if present.
    @OptionalField(key: "text_body")
    public var textBody: String?

    /// The decoded `text/html` part of the message body, if present.
    @OptionalField(key: "html_body")
    public var htmlBody: String?

    /// The ``Blob`` holding the raw MIME source of this email.
    ///
    /// The raw source is preserved so that re-parsing, signature verification,
    /// or forensic inspection remain possible after ingestion.
    @Parent(key: "raw_blob_id")
    public var rawBlob: Blob

    /// SES spam verdict. One of `PASS`, `FAIL`, `GRAY`, `PROCESSING_FAILED`, `DISABLED`.
    @Field(key: "spam_verdict")
    public var spamVerdict: String

    /// SES virus verdict. One of `PASS`, `FAIL`, `GRAY`, `PROCESSING_FAILED`, `DISABLED`.
    @Field(key: "virus_verdict")
    public var virusVerdict: String

    /// SES DKIM verdict. One of `PASS`, `FAIL`, `GRAY`, `PROCESSING_FAILED`, `DISABLED`.
    @Field(key: "dkim_verdict")
    public var dkimVerdict: String

    /// SES DMARC verdict. One of `PASS`, `FAIL`, `GRAY`, `PROCESSING_FAILED`, `DISABLED`.
    @Field(key: "dmarc_verdict")
    public var dmarcVerdict: String

    /// When SES reported that it received the message, not when the row was inserted.
    @Field(key: "received_at")
    public var receivedAt: Date

    /// When an operator first acknowledged this message in the inbox UI, or `nil`
    /// if still unread.
    ///
    /// `EmailMessageRepository.countUnread(toAddress:)` filters on `acknowledged_at IS NULL`
    /// to drive the inbox-badge count. The admin UI stamps this column when an
    /// operator opens the message.
    @OptionalField(key: "acknowledged_at")
    public var acknowledgedAt: Date?

    /// When the row was first written to the database.
    @Timestamp(key: "inserted_at", on: .create)
    public var insertedAt: Date?

    /// When the row was most recently updated.
    @Timestamp(key: "updated_at", on: .update)
    public var updatedAt: Date?

    public init() {
        self.references = []
        self.ccAddresses = []
        self.bccAddresses = []
    }
}
