import FluentKit
import Foundation

/// One decoded MIME attachment part belonging to an ``EmailMessage``.
///
/// Each row holds the metadata the application needs for display and search
/// (``filename``, ``contentType``, ``sizeBytes``) plus a ``Blob`` reference to
/// the decoded bytes. Inline images referenced from the HTML body carry a
/// ``contentId`` matching the `Content-ID` header so they can be resolved via
/// `cid:` URIs at render time.
public final class EmailAttachment: Model, @unchecked Sendable {
    public static let schema = "email_attachments"

    /// The unique identifier for this attachment, generated by the database.
    @ID(key: .id)
    public var id: UUID?

    /// The ``EmailMessage`` this attachment belongs to.
    @Parent(key: "email_message_id")
    public var emailMessage: EmailMessage

    /// The ``Blob`` holding the decoded attachment bytes in object storage.
    @Parent(key: "blob_id")
    public var blob: Blob

    /// The filename declared by the sender (`Content-Disposition: filename=`).
    @Field(key: "filename")
    public var filename: String

    /// The declared MIME type — e.g. `application/pdf`, `image/png`.
    @Field(key: "content_type")
    public var contentType: String

    /// The decoded attachment size in bytes.
    @Field(key: "size_bytes")
    public var sizeBytes: Int64

    /// The RFC 2392 `Content-ID` of this part, if the attachment is an inline
    /// resource referenced from the HTML body via `cid:` URIs.
    @OptionalField(key: "content_id")
    public var contentId: String?

    /// When the row was first written to the database.
    @Timestamp(key: "inserted_at", on: .create)
    public var insertedAt: Date?

    /// When the row was most recently updated.
    @Timestamp(key: "updated_at", on: .update)
    public var updatedAt: Date?

    public init() {}
}
