import FluentKit
import Foundation

/// Links a Navigator ``Entity`` to a billing provider's contact record.
///
/// A billing profile is a Navigator-owned link row, not a mirror of the
/// provider-side contact. It carries only the provider identifier and the
/// provider's contact UUID so that downstream tables (such as `invoices`)
/// can key off a single Navigator row rather than repeating the
/// `(provider, external_contact_id)` pair on every child.
///
/// One entity may have zero or one profile per provider — enforced by the
/// `UNIQUE (entity_id, provider)` constraint. The provider-side contact
/// UUID is globally unique across Navigator via
/// `UNIQUE (provider, external_contact_id)`, so a single Xero contact
/// cannot be mirrored by two entities.
///
/// Because this row is Navigator-owned rather than a mirror, it does not
/// carry `external_created_at`/`external_updated_at`/`synced_at` — those
/// are reserved for tables that reflect upstream provider state (see
/// `Invoice`).
public final class EntityBillingProfile: Model, @unchecked Sendable {
    public static let schema = "entity_billing_profiles"

    /// The unique identifier for this billing profile, generated by the database.
    @ID(key: .id)
    public var id: UUID?

    /// The Navigator ``Entity`` whose billing relationship this profile represents.
    @Parent(key: "entity_id")
    public var entity: Entity

    /// The billing provider backing this profile (e.g. Xero).
    ///
    /// Constrained to the ``BillingProvider`` enum set at the database level
    /// via a Postgres CHECK constraint.
    @Field(key: "provider")
    public var provider: BillingProvider

    /// The provider-side contact identifier — for Xero, the `ContactID` UUID
    /// string returned by the Contacts API.
    @Field(key: "external_contact_id")
    public var externalContactId: String

    /// When the row was first written to the database.
    @Timestamp(key: "inserted_at", on: .create)
    public var insertedAt: Date?

    /// When the row was most recently updated.
    @Timestamp(key: "updated_at", on: .update)
    public var updatedAt: Date?

    public init() {}
}

/// The set of billing providers Navigator can mirror.
///
/// Initially only Xero is supported. The raw value is persisted verbatim in
/// the `entity_billing_profiles.provider` column and pinned to this enum
/// set by a Postgres CHECK constraint named
/// `entity_billing_profiles_provider_check`.
public enum BillingProvider: String, Codable, CaseIterable, Sendable {
    case xero = "xero"
}
