import FluentKit
import Foundation

/// Mirror of an upstream billing provider's invoice header (Xero first).
///
/// `Invoice` rows are written by the Reporting Xero→Navigator sync Lambda
/// via ``InvoiceRepository/upsert(externalInvoiceId:billingProfileId:payload:)``.
/// Navigator never originates an invoice — the upstream provider is the
/// system of record.
///
/// Idempotency: the sync keys off
/// `UNIQUE (billing_profile_id, external_invoice_id)`.
/// `externalUpdatedAt` drives the skip-work short-circuit — when the Xero
/// `UpdatedDateUTC` has not advanced past the mirrored value, the business
/// fields are left untouched.
///
/// Observability: `syncedAt` records *every* reconciliation attempt
/// regardless of whether business fields changed, so operators can tell
/// "was this row checked recently?" from "did this row actually change
/// recently?".
///
/// There is deliberately no `externalCreatedAt` field: the Xero invoice
/// payload does not expose a creation timestamp, only `UpdatedDateUTC`.
///
/// Monetary fields use `Decimal` so Postgres `NUMERIC(19,4)` values
/// round-trip with no precision loss. The SQLite test harness stores them
/// as textual JSON, which also preserves exact decimal digits.
public final class Invoice: Model, @unchecked Sendable {
    public static let schema = "invoices"

    /// The unique identifier for this invoice mirror row, generated by the database.
    @ID(key: .id)
    public var id: UUID?

    /// The ``EntityBillingProfile`` that owns this invoice — the link row
    /// back to the Navigator ``Entity`` the invoice is billed to, scoped by
    /// provider.
    @Parent(key: "billing_profile_id")
    public var billingProfile: EntityBillingProfile

    /// The provider-side invoice identifier. For Xero, this is the
    /// `InvoiceID` UUID string returned by the Invoices API.
    @Field(key: "external_invoice_id")
    public var externalInvoiceId: String

    /// The human-readable invoice number assigned by the provider
    /// (Xero `InvoiceNumber`). Nullable for drafts that have not yet been
    /// numbered.
    @OptionalField(key: "invoice_number")
    public var invoiceNumber: String?

    /// Optional free-text reference the issuer attached to the invoice.
    @OptionalField(key: "reference")
    public var reference: String?

    /// Lifecycle state of the invoice on the provider side.
    @Field(key: "status")
    public var status: InvoiceStatus

    /// Which direction the invoice flows — accounts receivable (`accrec`,
    /// money coming in) vs accounts payable (`accpay`, money going out).
    @Field(key: "invoice_type")
    public var invoiceType: InvoiceType

    /// ISO-4217 three-letter currency code (e.g. `USD`). Pinned to 3
    /// characters via a Postgres CHECK constraint.
    @Field(key: "currency_code")
    public var currencyCode: String

    /// The business date of the invoice as stored by the provider
    /// (Xero `Date`). Calendar date only — the provider does not expose a
    /// time component on this field.
    @Field(key: "invoice_date")
    public var invoiceDate: Date

    /// The date payment is due, if the provider set one (Xero `DueDate`).
    @OptionalField(key: "due_date")
    public var dueDate: Date?

    /// Invoice total before tax (Xero `SubTotal`).
    @Field(key: "sub_total")
    public var subTotal: Decimal

    /// Total tax charged on the invoice (Xero `TotalTax`).
    @Field(key: "total_tax")
    public var totalTax: Decimal

    /// Invoice total including tax (Xero `Total`).
    @Field(key: "total")
    public var total: Decimal

    /// Remaining amount unpaid (Xero `AmountDue`).
    @Field(key: "amount_due")
    public var amountDue: Decimal

    /// Amount already paid (Xero `AmountPaid`).
    @Field(key: "amount_paid")
    public var amountPaid: Decimal

    /// Amount credited back via credit notes (Xero `AmountCredited`).
    @Field(key: "amount_credited")
    public var amountCredited: Decimal

    /// Optional reference to the ``Blob`` holding the Xero-rendered PDF of
    /// this invoice in S3. Populated by the Reporting sync Lambda once it
    /// has fetched and uploaded the PDF.
    @OptionalParent(key: "pdf_blob_id")
    public var pdfBlob: Blob?

    /// The upstream provider's last-modified timestamp (Xero
    /// `UpdatedDateUTC`). Drives the upsert skip-work short-circuit: if the
    /// payload's `externalUpdatedAt` does not advance past this value, the
    /// business fields are left untouched.
    @Field(key: "external_updated_at")
    public var externalUpdatedAt: Date

    /// When the sync job last reconciled this row — recorded on *every*
    /// upsert attempt, regardless of whether any business field changed.
    @Field(key: "synced_at")
    public var syncedAt: Date

    /// When the row was first written to the database.
    @Timestamp(key: "inserted_at", on: .create)
    public var insertedAt: Date?

    /// When the row was most recently updated.
    @Timestamp(key: "updated_at", on: .update)
    public var updatedAt: Date?

    public init() {}
}

/// Lifecycle state of an ``Invoice`` on the provider side.
///
/// Constrained to this enum set at the database level via the
/// `invoices_status_check` Postgres CHECK constraint.
public enum InvoiceStatus: String, Codable, CaseIterable, Sendable {
    case draft = "draft"
    case submitted = "submitted"
    case authorised = "authorised"
    case paid = "paid"
    case voided = "voided"
    case deleted = "deleted"
}

/// The direction of an ``Invoice`` — receivable or payable.
///
/// Constrained to this enum set at the database level via the
/// `invoices_invoice_type_check` Postgres CHECK constraint.
public enum InvoiceType: String, Codable, CaseIterable, Sendable {
    /// Accounts receivable — money owed to the business (sales invoice).
    case accrec = "accrec"
    /// Accounts payable — money the business owes (bill).
    case accpay = "accpay"
}
