import FluentKit
import Foundation

/// One line item on an ``Invoice`` mirror row.
///
/// `InvoiceLineItem` rows are managed exclusively through
/// ``InvoiceLineItemRepository/replaceAll(forInvoiceId:with:)``: every Xero
/// sync deletes the entire set for the parent invoice and re-inserts the
/// payloads in a single transaction. Lines are **never** merged per row,
/// even when their `external_line_item_id` matches an existing value, because
/// Xero's invoice payload returns the complete line-item array on every
/// fetch and exposes no per-line stable upstream identity that Navigator
/// trusts as a merge key.
///
/// As a consequence, `id` values for line items are not stable across syncs
/// — a row with the same business content as a previous row will have a new
/// primary key after a re-sync. Downstream code must not treat
/// `invoice_line_items.id` as a long-lived reference.
///
/// Cascade delete: the table's `invoice_id` foreign key is declared
/// `ON DELETE CASCADE`, so deleting an ``Invoice`` removes its line items
/// automatically. There is no orphan-line state.
///
/// No `external_*` timestamps live on this row: Xero does not expose
/// per-line-item modification timestamps, and since the entire set is
/// replaced atomically the parent ``Invoice/externalUpdatedAt`` already
/// captures the effective change time.
public final class InvoiceLineItem: Model, @unchecked Sendable {
    public static let schema = "invoice_line_items"

    /// The unique identifier for this line-item row, generated by the
    /// database. Not stable across re-syncs — see the type-level note on
    /// full-replace semantics.
    @ID(key: .id)
    public var id: UUID?

    /// The ``Invoice`` this line item belongs to. The foreign key is
    /// `ON DELETE CASCADE`.
    @Parent(key: "invoice_id")
    public var invoice: Invoice

    /// 1-based ordering of this line within its invoice.
    @Field(key: "line_number")
    public var lineNumber: Int32

    /// The Xero `LineItemID` for this line, captured for traceability only.
    /// Not used as a merge key — see the type-level note.
    @OptionalField(key: "external_line_item_id")
    public var externalLineItemId: String?

    /// The free-text description shown on the invoice line.
    @Field(key: "description")
    public var description: String

    /// Optional inventory item code (Xero `ItemCode`).
    @OptionalField(key: "item_code")
    public var itemCode: String?

    /// Optional ledger account code (Xero `AccountCode`).
    @OptionalField(key: "account_code")
    public var accountCode: String?

    /// Quantity for this line (Xero `Quantity`).
    @Field(key: "quantity")
    public var quantity: Decimal

    /// Unit amount for this line (Xero `UnitAmount`).
    @Field(key: "unit_amount")
    public var unitAmount: Decimal

    /// Optional Xero tax-type code (e.g. `OUTPUT`, `NONE`).
    @OptionalField(key: "tax_type")
    public var taxType: String?

    /// Tax amount for this line (Xero `TaxAmount`).
    @Field(key: "tax_amount")
    public var taxAmount: Decimal

    /// Total amount for this line, post-discount, pre-tax (Xero `LineAmount`).
    @Field(key: "line_amount")
    public var lineAmount: Decimal

    /// Optional discount rate applied to this line (Xero `DiscountRate`).
    @OptionalField(key: "discount_rate")
    public var discountRate: Decimal?

    /// When the row was first written to the database.
    @Timestamp(key: "inserted_at", on: .create)
    public var insertedAt: Date?

    /// When the row was most recently updated. Effectively the same as
    /// `insertedAt` in practice, since rows are deleted-and-reinserted on
    /// every sync.
    @Timestamp(key: "updated_at", on: .update)
    public var updatedAt: Date?

    public init() {}
}
