import FluentKit
import Foundation

/// A permanent record of a role change made to a ``User`` by an administrator.
///
/// Every time an admin changes another user's role via the role-management API,
/// a `UserRoleAudit` row is written capturing who made the change, what the
/// previous and new roles were, and the reason provided. This creates an
/// immutable audit trail that satisfies two requirements:
///
/// - **Accountability**: staff and compliance can trace every privilege
///   escalation or demotion back to a specific administrator and reason.
/// - **Reversibility**: if a role change causes issues, the history shows
///   exactly what to revert and why the original change was made.
///
/// Audit rows are append-only — they are never updated or deleted.
///
/// ## Topics
///
/// ### Properties
///
/// - ``id``
/// - ``user``
/// - ``changedByUser``
/// - ``previousRole``
/// - ``newRole``
/// - ``reason``
/// - ``insertedAt``
public final class UserRoleAudit: Model, @unchecked Sendable {
    public static let schema = "user_role_audit"

    /// The unique identifier for this audit record, generated by the database.
    @ID(key: .id)
    public var id: UUID?

    /// The user whose role was changed.
    @Parent(key: "user_id")
    public var user: User

    /// The administrator who performed the role change.
    @Parent(key: "changed_by_user_id")
    public var changedByUser: User

    /// The role the user held before the change.
    @Field(key: "previous_role")
    public var previousRole: UserRole

    /// The role the user was changed to.
    @Field(key: "new_role")
    public var newRole: UserRole

    /// The administrator's stated reason for making this change.
    @Field(key: "reason")
    public var reason: String

    /// The timestamp when this role change occurred.
    @Timestamp(key: "inserted_at", on: .create)
    public var insertedAt: Date?

    /// Equal to `insertedAt` for unmodified rows — `UserRoleAudit` is
    /// append-only by service-layer convention. The column is present so
    /// every table satisfies the `inserted_at` / `updated_at` schema invariant.
    @Timestamp(key: "updated_at", on: .update)
    public var updatedAt: Date?

    public init() {}
}
