//! Mint and validate single-use, expiring [`email_token`]s — the link
//! in a "reset your password" or "confirm your email" message.
//!
//! Mirrors [`crate::git_access_tokens`]: `store` stays free of
//! randomness, so the random plaintext is generated by the caller
//! (`web::session::random_token_32`) and passed in; this module only
//! hashes it, persists the hash, and looks it back up. The plaintext is
//! surfaced once in the emailed URL and never stored — only its SHA-256
//! hex. Single use is enforced by stamping [`email_token::Model::used_at`]
//! on claim ([`consume`]); expiry is the other gate ([`validate`]).
//!
//! The hash is shared with [`crate::git_access_tokens::hash_token`] so
//! there is one token-hashing seam in the workspace, not two.

use chrono::{DateTime, Utc};
use sea_orm::{ActiveModelTrait, ActiveValue, ColumnTrait, EntityTrait, QueryFilter, QueryOrder};
use uuid::Uuid;

use crate::entity::email_token;
use crate::git_access_tokens::hash_token;
use crate::Db;

/// Errors minting, validating, or consuming a token.
#[derive(Debug, thiserror::Error)]
pub enum TokenError {
    /// A database operation failed.
    #[error("database: {0}")]
    Db(#[from] sea_orm::DbErr),
}

/// Persist a freshly minted token and return the stored row. The caller
/// owns the random `plaintext` and emails it once; only its hash is
/// stored. `purpose` is one of the
/// [`email_token::PURPOSE_PASSWORD_RESET`] /
/// [`email_token::PURPOSE_EMAIL_CONFIRM`] constants.
///
/// # Errors
/// [`TokenError::Db`] if the insert fails.
pub async fn mint(
    db: &Db,
    person_id: Uuid,
    email: &str,
    purpose: &str,
    plaintext: &str,
    expires_at: DateTime<Utc>,
) -> Result<email_token::Model, TokenError> {
    let model = email_token::ActiveModel {
        person_id: ActiveValue::Set(person_id),
        email: ActiveValue::Set(email.to_string()),
        purpose: ActiveValue::Set(purpose.to_string()),
        token_hash: ActiveValue::Set(hash_token(plaintext)),
        expires_at: ActiveValue::Set(expires_at.to_rfc3339()),
        used_at: ActiveValue::Set(None),
        ..Default::default()
    }
    .insert(db)
    .await?;
    Ok(model)
}

/// Resolve a presented token plaintext to its row, or `None` if there
/// is no such token, it is for a different `purpose`, it has already
/// been claimed, or it has expired at `now`. A spent or expired token
/// is treated exactly as an absent one — the caller shows the same
/// "this link is no longer valid" page either way, so the response can
/// never be used to probe which case occurred.
///
/// # Errors
/// [`TokenError::Db`] if the lookup fails.
pub async fn validate(
    db: &Db,
    plaintext: &str,
    purpose: &str,
    now: DateTime<Utc>,
) -> Result<Option<email_token::Model>, TokenError> {
    let hash = hash_token(plaintext);
    let Some(model) = email_token::Entity::find()
        .filter(email_token::Column::TokenHash.eq(hash))
        .filter(email_token::Column::Purpose.eq(purpose))
        .one(db)
        .await?
    else {
        return Ok(None);
    };
    // Single use: a claimed token is dead even before it expires.
    if model.used_at.is_some() {
        return Ok(None);
    }
    // Expiry: parse the stored RFC 3339 instant and compare. A row whose
    // timestamp won't parse is treated as expired rather than trusted.
    let live = DateTime::parse_from_rfc3339(&model.expires_at).is_ok_and(|exp| exp > now);
    Ok(live.then_some(model))
}

/// Mark a token spent by stamping `used_at = now`. Single-use is then
/// enforced by [`validate`], which treats any `used_at`-set row as
/// absent. Idempotent in effect — re-stamping a spent token is
/// harmless.
///
/// # Errors
/// [`TokenError::Db`] if the update fails.
pub async fn consume(db: &Db, token_id: Uuid, now: DateTime<Utc>) -> Result<(), TokenError> {
    let Some(model) = email_token::Entity::find_by_id(token_id).one(db).await? else {
        return Ok(());
    };
    let mut update: email_token::ActiveModel = model.into();
    update.used_at = ActiveValue::Set(Some(now.to_rfc3339()));
    update.update(db).await?;
    Ok(())
}

/// True if the person already has a live (unused, unexpired) token of
/// this `purpose` minted at or after `since`. Backs the per-person mint
/// throttle: the request handler skips minting a second link inside the
/// throttle window so a flood of "reset" submissions can't spray a
/// mailbox.
///
/// # Errors
/// [`TokenError::Db`] if the lookup fails.
pub async fn has_live_token_since(
    db: &Db,
    person_id: Uuid,
    purpose: &str,
    since: DateTime<Utc>,
    now: DateTime<Utc>,
) -> Result<bool, TokenError> {
    let rows = email_token::Entity::find()
        .filter(email_token::Column::PersonId.eq(person_id))
        .filter(email_token::Column::Purpose.eq(purpose))
        .order_by_desc(email_token::Column::InsertedAt)
        .all(db)
        .await?;
    let hit = rows.into_iter().any(|m| {
        if m.used_at.is_some() {
            return false;
        }
        let live = DateTime::parse_from_rfc3339(&m.expires_at).is_ok_and(|exp| exp > now);
        let recent = DateTime::parse_from_rfc3339(&m.inserted_at).is_ok_and(|ins| ins >= since);
        live && recent
    });
    Ok(hit)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::entity::{email_token, person};
    use crate::test_support::pg;
    use chrono::Duration;

    async fn a_person(db: &Db) -> Uuid {
        person::ActiveModel {
            name: ActiveValue::Set("Libra".into()),
            email: ActiveValue::Set("libra@example.com".into()),
            ..Default::default()
        }
        .insert(db)
        .await
        .unwrap()
        .id
    }

    #[tokio::test]
    async fn mint_then_validate_resolves_person_and_purpose() {
        let db = pg().await;
        let person_id = a_person(&db).await;
        let now = Utc::now();

        let minted = mint(
            &db,
            person_id,
            "libra@example.com",
            email_token::PURPOSE_PASSWORD_RESET,
            "the-plaintext-secret",
            now + Duration::minutes(30),
        )
        .await
        .unwrap();

        // The plaintext is never stored — only its hash.
        assert_eq!(minted.token_hash, hash_token("the-plaintext-secret"));
        assert!(minted.used_at.is_none());

        let resolved = validate(
            &db,
            "the-plaintext-secret",
            email_token::PURPOSE_PASSWORD_RESET,
            now,
        )
        .await
        .unwrap()
        .expect("valid token resolves");
        assert_eq!(resolved.person_id, person_id);
        assert_eq!(resolved.email, "libra@example.com");
    }

    #[tokio::test]
    async fn validate_is_scoped_to_the_purpose() {
        let db = pg().await;
        let person_id = a_person(&db).await;
        let now = Utc::now();

        mint(
            &db,
            person_id,
            "libra@example.com",
            email_token::PURPOSE_EMAIL_CONFIRM,
            "confirm-token",
            now + Duration::minutes(30),
        )
        .await
        .unwrap();

        // A reset-purpose validate must not accept a confirm-purpose token.
        assert!(validate(
            &db,
            "confirm-token",
            email_token::PURPOSE_PASSWORD_RESET,
            now
        )
        .await
        .unwrap()
        .is_none());
        // …but the matching purpose does.
        assert!(validate(
            &db,
            "confirm-token",
            email_token::PURPOSE_EMAIL_CONFIRM,
            now
        )
        .await
        .unwrap()
        .is_some());
    }

    #[tokio::test]
    async fn unknown_token_does_not_validate() {
        let db = pg().await;
        let resolved = validate(
            &db,
            "never-minted",
            email_token::PURPOSE_PASSWORD_RESET,
            Utc::now(),
        )
        .await
        .unwrap();
        assert!(resolved.is_none());
    }

    #[tokio::test]
    async fn expired_token_is_treated_as_absent() {
        let db = pg().await;
        let person_id = a_person(&db).await;
        let now = Utc::now();

        mint(
            &db,
            person_id,
            "libra@example.com",
            email_token::PURPOSE_PASSWORD_RESET,
            "already-expired",
            now - Duration::seconds(1),
        )
        .await
        .unwrap();

        let resolved = validate(
            &db,
            "already-expired",
            email_token::PURPOSE_PASSWORD_RESET,
            now,
        )
        .await
        .unwrap();
        assert!(resolved.is_none(), "an expired token must not validate");
    }

    #[tokio::test]
    async fn consumed_token_stops_validating() {
        let db = pg().await;
        let person_id = a_person(&db).await;
        let now = Utc::now();

        let minted = mint(
            &db,
            person_id,
            "libra@example.com",
            email_token::PURPOSE_PASSWORD_RESET,
            "single-use",
            now + Duration::minutes(30),
        )
        .await
        .unwrap();

        assert!(
            validate(&db, "single-use", email_token::PURPOSE_PASSWORD_RESET, now)
                .await
                .unwrap()
                .is_some()
        );
        consume(&db, minted.id, now).await.unwrap();
        assert!(
            validate(&db, "single-use", email_token::PURPOSE_PASSWORD_RESET, now)
                .await
                .unwrap()
                .is_none(),
            "a consumed token must not validate again"
        );
    }

    #[tokio::test]
    async fn throttle_sees_a_live_token_inside_the_window_only() {
        let db = pg().await;
        let person_id = a_person(&db).await;
        let now = Utc::now();

        // No token yet → nothing live.
        assert!(!has_live_token_since(
            &db,
            person_id,
            email_token::PURPOSE_PASSWORD_RESET,
            now - Duration::seconds(60),
            now,
        )
        .await
        .unwrap());

        let minted = mint(
            &db,
            person_id,
            "libra@example.com",
            email_token::PURPOSE_PASSWORD_RESET,
            "fresh",
            now + Duration::minutes(30),
        )
        .await
        .unwrap();

        // A just-minted token is inside a 60s look-back window.
        assert!(has_live_token_since(
            &db,
            person_id,
            email_token::PURPOSE_PASSWORD_RESET,
            now - Duration::seconds(60),
            now,
        )
        .await
        .unwrap());

        // Once consumed it no longer counts against the throttle.
        consume(&db, minted.id, now).await.unwrap();
        assert!(!has_live_token_since(
            &db,
            person_id,
            email_token::PURPOSE_PASSWORD_RESET,
            now - Duration::seconds(60),
            now,
        )
        .await
        .unwrap());
    }
}
