//! Mint and validate single-use, expiring email tokens — the link in a
//! "reset your password" or "confirm your email" message.
//!
//! Mirrors [`crate::git_access_tokens`]: `store` stays free of
//! randomness, so the random plaintext is generated by the caller
//! (`portal::session::random_token_32`) and passed in; this module only
//! hashes it, persists the hash, and looks it back up. The plaintext is
//! surfaced once in the emailed URL and never stored — only its SHA-256
//! hex. Single use is enforced by stamping [`EmailToken::used_at`] on
//! claim ([`consume`]); expiry is the other gate ([`validate`]).
//!
//! The hash is shared with [`crate::git_access_tokens::hash_token`] so
//! there is one token-hashing seam in the workspace, not two.
//!
//! # This table lives in SurrealDB
//!
//! `email_token` is the first table the phase-3 port moved (#1093,
//! #1159). Two consequences are visible in the signatures below.
//!
//! `person_id` is a `record<person>` link now that the person row exists
//! in this engine (ENG-19). It stays a [`Uuid`] in this module's
//! signatures: a caller logging `person_id` or passing one in should not
//! have to know how the engine spells a key. Note the engine does not
//! validate a link against an existing row, so a token minted for a
//! person that was never written is accepted here.
//!
//! The instants are native `datetime` rather than RFC 3339 strings, so the
//! engine parses them on write and an unparseable stored timestamp is
//! unrepresentable. Nothing downstream has to treat one as expired.

use chrono::{DateTime, Utc};
use surrealdb::types::SurrealValue;
use uuid::Uuid;

use crate::git_access_tokens::hash_token;
use crate::surreal::{record_id, SurrealDb};

/// The token in a "reset your password" email. Claiming it lets the
/// holder set a new password in Identity Platform for the account.
pub const PURPOSE_PASSWORD_RESET: &str = "password_reset";
/// The token in a "confirm your email" email. Claiming it flips
/// `emailVerified` in Identity Platform for the account.
pub const PURPOSE_EMAIL_CONFIRM: &str = "email_confirm";

/// The table these rows live in.
const TABLE: &str = "email_token";
/// The table `person_id` links into.
const PERSON_TABLE: &str = "person";

/// Errors minting, validating, or consuming a token.
#[derive(Debug, thiserror::Error)]
pub enum TokenError {
    /// A database operation failed.
    #[error("database: {0}")]
    Db(#[from] surrealdb::Error),
    /// `CREATE` reported success but returned no row, or returned one
    /// whose record id is not a native UUID key. Neither is a state a
    /// caller can act on, and neither is reachable through this
    /// module's own writes — it means the row was written by something
    /// that bypassed [`crate::surreal::record_id`].
    #[error("minting an email token returned no usable row")]
    MintReturnedNothing,
}

/// A minted token row, as callers read it back.
///
/// `id` and `person_id` are `Uuid` at this boundary even though the
/// engine stores the record id as a native UUID record key — a caller
/// logging `person_id` or passing `id` back to [`consume`] should not
/// have to know which engine answered.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EmailToken {
    pub id: Uuid,
    pub person_id: Uuid,
    pub email: String,
    pub purpose: String,
    pub token_hash: String,
    pub expires_at: DateTime<Utc>,
    pub used_at: Option<DateTime<Utc>>,
    pub inserted_at: DateTime<Utc>,
}

/// The row as the engine reads and writes it. Separate from
/// [`EmailToken`] because the SDK owns its own `Uuid` and `Datetime`,
/// and the conversion belongs at this seam rather than in every caller.
#[derive(SurrealValue)]
struct EmailTokenRow {
    id: surrealdb::types::RecordId,
    person_id: surrealdb::types::RecordId,
    email: String,
    purpose: String,
    token_hash: String,
    expires_at: surrealdb::types::Datetime,
    used_at: Option<surrealdb::types::Datetime>,
    inserted_at: surrealdb::types::Datetime,
}

impl EmailTokenRow {
    /// `None` when the record id is not a native UUID key — a row
    /// written with the string spelling [`crate::surreal::record_id`]
    /// cannot produce. See that module for why the two differ.
    fn into_token(self) -> Option<EmailToken> {
        Some(EmailToken {
            id: crate::surreal::record_uuid(&self.id)?,
            person_id: crate::surreal::record_uuid(&self.person_id)?,
            email: self.email,
            purpose: self.purpose,
            token_hash: self.token_hash,
            expires_at: self.expires_at.into(),
            used_at: self.used_at.map(Into::into),
            inserted_at: self.inserted_at.into(),
        })
    }
}

/// Persist a freshly minted token and return the stored row. The caller
/// owns the random `plaintext` and emails it once; only its hash is
/// stored. `purpose` is one of the [`PURPOSE_PASSWORD_RESET`] /
/// [`PURPOSE_EMAIL_CONFIRM`] constants.
///
/// # Errors
/// [`TokenError::Db`] if the insert fails.
pub async fn mint(
    db: &SurrealDb,
    person_id: Uuid,
    email: &str,
    purpose: &str,
    plaintext: &str,
    expires_at: DateTime<Utc>,
) -> Result<EmailToken, TokenError> {
    let id = Uuid::now_v7();
    let mut response = db
        .query(format!(
            "CREATE $id SET \
             person_id = $person_id, \
             email = $email, \
             purpose = $purpose, \
             token_hash = $token_hash, \
             expires_at = $expires_at, \
             used_at = NONE \
             RETURN {SELECT}"
        ))
        .bind(("id", record_id(TABLE, id)))
        .bind(("person_id", record_id(PERSON_TABLE, person_id)))
        .bind(("email", email.to_string()))
        .bind(("purpose", purpose.to_string()))
        .bind(("token_hash", hash_token(plaintext)))
        .bind(("expires_at", surrealdb::types::Datetime::from(expires_at)))
        .await
        .and_then(surrealdb::IndexedResults::check)?;

    let row: Option<EmailTokenRow> = response.take(0)?;
    row.and_then(EmailTokenRow::into_token)
        .ok_or(TokenError::MintReturnedNothing)
}

/// Resolve a presented token plaintext to its row, or `None` if there
/// is no such token, it is for a different `purpose`, it has already
/// been claimed, or it has expired at `now`. A spent or expired token
/// is treated exactly as an absent one — the caller shows the same
/// "this link is no longer valid" page either way, so the response can
/// never be used to probe which case occurred.
///
/// # Errors
/// [`TokenError::Db`] if the lookup fails.
pub async fn validate(
    db: &SurrealDb,
    plaintext: &str,
    purpose: &str,
    now: DateTime<Utc>,
) -> Result<Option<EmailToken>, TokenError> {
    // Single use and expiry are both engine-side: `used_at = NONE` and
    // `expires_at > $now` are the two gates, applied in the query rather
    // than in Rust after loading the row.
    let mut response = db
        .query(format!(
            "SELECT {SELECT} FROM {TABLE} \
             WHERE token_hash = $hash \
             AND purpose = $purpose \
             AND used_at IS NONE \
             AND expires_at > $now \
             LIMIT 1"
        ))
        .bind(("hash", hash_token(plaintext)))
        .bind(("purpose", purpose.to_string()))
        .bind(("now", surrealdb::types::Datetime::from(now)))
        .await
        .and_then(surrealdb::IndexedResults::check)?;

    let rows: Vec<EmailTokenRow> = response.take(0)?;
    Ok(rows.into_iter().next().and_then(EmailTokenRow::into_token))
}

/// Mark a token spent by stamping `used_at = now`. Single-use is then
/// enforced by [`validate`], which treats any `used_at`-set row as
/// absent. Idempotent in effect — re-stamping a spent token is
/// harmless, and stamping one that does not exist is a no-op.
///
/// # Errors
/// [`TokenError::Db`] if the update fails.
pub async fn consume(db: &SurrealDb, token_id: Uuid, now: DateTime<Utc>) -> Result<(), TokenError> {
    db.query(format!(
        "UPDATE $id SET used_at = $now, updated_at = $now RETURN {SELECT}"
    ))
    .bind(("id", record_id(TABLE, token_id)))
    .bind(("now", surrealdb::types::Datetime::from(now)))
    .await
    .and_then(surrealdb::IndexedResults::check)?;
    Ok(())
}

/// True if the person already has a live (unused, unexpired) token of
/// this `purpose` minted at or after `since`. Backs the per-person mint
/// throttle: the request handler skips minting a second link inside the
/// throttle window so a flood of "reset" submissions can't spray a
/// mailbox.
///
/// # Errors
/// [`TokenError::Db`] if the lookup fails.
pub async fn has_live_token_since(
    db: &SurrealDb,
    person_id: Uuid,
    purpose: &str,
    since: DateTime<Utc>,
    now: DateTime<Utc>,
) -> Result<bool, TokenError> {
    let mut response = db
        .query(format!(
            "SELECT VALUE count() FROM {TABLE} \
             WHERE person_id = $person_id \
             AND purpose = $purpose \
             AND used_at IS NONE \
             AND expires_at > $now \
             AND inserted_at >= $since \
             GROUP ALL"
        ))
        .bind(("person_id", record_id(PERSON_TABLE, person_id)))
        .bind(("purpose", purpose.to_string()))
        .bind(("now", surrealdb::types::Datetime::from(now)))
        .bind(("since", surrealdb::types::Datetime::from(since)))
        .await
        .and_then(surrealdb::IndexedResults::check)?;

    let counts: Vec<i64> = response.take(0)?;
    Ok(counts.first().is_some_and(|count| *count > 0))
}

/// The projection every read shares, so one field list describes the
/// row and a new column cannot reach [`EmailTokenRow`] from only one
/// query.
const SELECT: &str = "id, person_id, email, purpose, token_hash, expires_at, used_at, inserted_at";

#[cfg(test)]
mod tests {
    use super::*;
    use crate::surreal::test_support::mem;
    use chrono::Duration;

    /// Nothing in this module dereferences the person a token acts on, so
    /// a bare id is the whole reference — which is the shape under test.
    fn a_person() -> Uuid {
        Uuid::now_v7()
    }

    #[tokio::test]
    async fn mint_then_validate_resolves_person_and_purpose() {
        let db = mem().await;
        let person_id = a_person();
        let now = Utc::now();

        let minted = mint(
            &db,
            person_id,
            "libra@example.com",
            PURPOSE_PASSWORD_RESET,
            "the-plaintext-secret",
            now + Duration::minutes(30),
        )
        .await
        .unwrap();

        // The plaintext is never stored — only its hash.
        assert_eq!(minted.token_hash, hash_token("the-plaintext-secret"));
        assert!(minted.used_at.is_none());

        let resolved = validate(&db, "the-plaintext-secret", PURPOSE_PASSWORD_RESET, now)
            .await
            .unwrap()
            .expect("valid token resolves");
        assert_eq!(resolved.person_id, person_id);
        assert_eq!(resolved.email, "libra@example.com");
    }

    #[tokio::test]
    async fn validate_is_scoped_to_the_purpose() {
        let db = mem().await;
        let now = Utc::now();

        mint(
            &db,
            a_person(),
            "libra@example.com",
            PURPOSE_EMAIL_CONFIRM,
            "confirm-token",
            now + Duration::minutes(30),
        )
        .await
        .unwrap();

        // A reset-purpose validate must not accept a confirm-purpose token.
        assert!(validate(&db, "confirm-token", PURPOSE_PASSWORD_RESET, now)
            .await
            .unwrap()
            .is_none());
        // …but the matching purpose does.
        assert!(validate(&db, "confirm-token", PURPOSE_EMAIL_CONFIRM, now)
            .await
            .unwrap()
            .is_some());
    }

    #[tokio::test]
    async fn unknown_token_does_not_validate() {
        let db = mem().await;
        let resolved = validate(&db, "never-minted", PURPOSE_PASSWORD_RESET, Utc::now())
            .await
            .unwrap();
        assert!(resolved.is_none());
    }

    #[tokio::test]
    async fn expired_token_is_treated_as_absent() {
        let db = mem().await;
        let now = Utc::now();

        mint(
            &db,
            a_person(),
            "libra@example.com",
            PURPOSE_PASSWORD_RESET,
            "already-expired",
            now - Duration::seconds(1),
        )
        .await
        .unwrap();

        let resolved = validate(&db, "already-expired", PURPOSE_PASSWORD_RESET, now)
            .await
            .unwrap();
        assert!(resolved.is_none(), "an expired token must not validate");
    }

    #[tokio::test]
    async fn consumed_token_stops_validating() {
        let db = mem().await;
        let now = Utc::now();

        let minted = mint(
            &db,
            a_person(),
            "libra@example.com",
            PURPOSE_PASSWORD_RESET,
            "single-use",
            now + Duration::minutes(30),
        )
        .await
        .unwrap();

        assert!(validate(&db, "single-use", PURPOSE_PASSWORD_RESET, now)
            .await
            .unwrap()
            .is_some());
        consume(&db, minted.id, now).await.unwrap();
        assert!(
            validate(&db, "single-use", PURPOSE_PASSWORD_RESET, now)
                .await
                .unwrap()
                .is_none(),
            "a consumed token must not validate again"
        );
    }

    #[tokio::test]
    async fn consuming_an_unknown_token_is_a_no_op() {
        let db = mem().await;
        consume(&db, Uuid::now_v7(), Utc::now()).await.unwrap();
    }

    #[tokio::test]
    async fn a_token_minted_before_the_window_does_not_satisfy_the_throttle() {
        let db = mem().await;
        let person_id = a_person();
        let now = Utc::now();

        mint(
            &db,
            person_id,
            "libra@example.com",
            PURPOSE_PASSWORD_RESET,
            "older-than-the-window",
            now + Duration::minutes(30),
        )
        .await
        .unwrap();

        // The token is live, but `since` is after it was minted. This is
        // the `inserted_at >= $since` half of the gate — without it the
        // throttle would suppress every later mint for as long as one
        // unexpired token survived, and a person who never received the
        // first email could not request a second.
        assert!(!has_live_token_since(
            &db,
            person_id,
            PURPOSE_PASSWORD_RESET,
            now + Duration::seconds(60),
            now,
        )
        .await
        .unwrap());
    }

    #[tokio::test]
    async fn throttle_sees_a_live_token_inside_the_window_only() {
        let db = mem().await;
        let person_id = a_person();
        let now = Utc::now();

        // No token yet → nothing live.
        assert!(!has_live_token_since(
            &db,
            person_id,
            PURPOSE_PASSWORD_RESET,
            now - Duration::seconds(60),
            now,
        )
        .await
        .unwrap());

        let minted = mint(
            &db,
            person_id,
            "libra@example.com",
            PURPOSE_PASSWORD_RESET,
            "fresh",
            now + Duration::minutes(30),
        )
        .await
        .unwrap();

        // A just-minted token is inside a 60s look-back window.
        assert!(has_live_token_since(
            &db,
            person_id,
            PURPOSE_PASSWORD_RESET,
            now - Duration::seconds(60),
            now,
        )
        .await
        .unwrap());

        // Once consumed it no longer counts against the throttle.
        consume(&db, minted.id, now).await.unwrap();
        assert!(!has_live_token_since(
            &db,
            person_id,
            PURPOSE_PASSWORD_RESET,
            now - Duration::seconds(60),
            now,
        )
        .await
        .unwrap());
    }

    #[tokio::test]
    async fn another_persons_live_token_does_not_satisfy_the_throttle() {
        let db = mem().await;
        let now = Utc::now();

        mint(
            &db,
            a_person(),
            "libra@example.com",
            PURPOSE_PASSWORD_RESET,
            "someone-elses",
            now + Duration::minutes(30),
        )
        .await
        .unwrap();

        assert!(!has_live_token_since(
            &db,
            a_person(),
            PURPOSE_PASSWORD_RESET,
            now - Duration::seconds(60),
            now,
        )
        .await
        .unwrap());
    }

    #[tokio::test]
    async fn the_purpose_assert_rejects_an_unknown_purpose() {
        let db = mem().await;
        let err = mint(
            &db,
            a_person(),
            "libra@example.com",
            "not_a_purpose",
            "bad",
            Utc::now() + Duration::minutes(30),
        )
        .await;
        assert!(
            err.is_err(),
            "the schema ASSERT is the gate on `purpose`, not a Rust check"
        );
    }
}
