//! Mint and validate Personal Access Tokens for the per-Project git
//! transport.
//!
//! A browser read of a repo rides the session cookie, but `git clone` /
//! `git push` from a CLI has no cookie — it sends HTTP Basic. `web`
//! mints one of these tokens, the lawyer pastes it into git's credential
//! helper, and `web` validates it where `/mcp` validates its bearer (one
//! token seam, not a parallel password store). See
//! [the design](../../docs/git-project-repos.md) §2.
//!
//! `store` deliberately stays free of randomness (see
//! [`crate::email_conversations`]): the random plaintext is generated by
//! the caller (`web::session::random_token_32`) and passed in; this
//! module only hashes it, persists the hash, and looks it back up. The
//! plaintext is shown to the lawyer once and never stored — only its
//! SHA-256 hex. Revocation is deleting the row ([`revoke`]).

use chrono::{DateTime, Utc};
use sea_orm::{ActiveModelTrait, ActiveValue, ColumnTrait, EntityTrait, QueryFilter};
use uuid::Uuid;

use crate::entity::git_access_token;
use crate::Db;

/// Errors minting or validating a token.
#[derive(Debug, thiserror::Error)]
pub enum TokenError {
    /// A database operation failed.
    #[error("database: {0}")]
    Db(#[from] sea_orm::DbErr),
}

/// SHA-256 hex of a token plaintext. Deterministic — the only thing
/// `store` does with a token, since it never generates one.
#[must_use]
pub fn hash_token(plaintext: &str) -> String {
    use sha2::{Digest, Sha256};
    use std::fmt::Write as _;
    let digest = Sha256::digest(plaintext.as_bytes());
    let mut out = String::with_capacity(64);
    for b in digest {
        let _ = write!(&mut out, "{b:02x}");
    }
    out
}

/// Persist a freshly minted token and return the stored row. The caller
/// owns the random `plaintext` and surfaces it once; only its hash is
/// stored. `project_id` of `None` scopes the token to every Project the
/// person participates in; `scope` is one of the
/// [`git_access_token::SCOPE_READ`] / [`git_access_token::SCOPE_WRITE`]
/// constants.
///
/// # Errors
/// [`TokenError::Db`] if the insert fails.
pub async fn mint(
    db: &Db,
    person_id: Uuid,
    project_id: Option<Uuid>,
    scope: &str,
    plaintext: &str,
    expires_at: DateTime<Utc>,
) -> Result<git_access_token::Model, TokenError> {
    let model = git_access_token::ActiveModel {
        person_id: ActiveValue::Set(person_id),
        project_id: ActiveValue::Set(project_id),
        token_hash: ActiveValue::Set(hash_token(plaintext)),
        scope: ActiveValue::Set(scope.to_string()),
        expires_at: ActiveValue::Set(expires_at.to_rfc3339()),
        ..Default::default()
    }
    .insert(db)
    .await?;
    Ok(model)
}

/// Resolve a presented token plaintext to its row, or `None` if there is
/// no such token or it has expired at `now`. An expired token is treated
/// exactly as an absent one — the caller returns `401` either way.
///
/// # Errors
/// [`TokenError::Db`] if the lookup fails.
pub async fn validate(
    db: &Db,
    plaintext: &str,
    now: DateTime<Utc>,
) -> Result<Option<git_access_token::Model>, TokenError> {
    let hash = hash_token(plaintext);
    let Some(model) = git_access_token::Entity::find()
        .filter(git_access_token::Column::TokenHash.eq(hash))
        .one(db)
        .await?
    else {
        return Ok(None);
    };
    // Expiry: parse the stored RFC 3339 instant and compare. A row whose
    // timestamp won't parse is treated as expired rather than trusted.
    let live = DateTime::parse_from_rfc3339(&model.expires_at).is_ok_and(|exp| exp > now);
    Ok(live.then_some(model))
}

/// Revoke a token by id (row deletion). Idempotent — deleting a token
/// that is already gone is not an error.
///
/// # Errors
/// [`TokenError::Db`] if the delete fails.
pub async fn revoke(db: &Db, token_id: Uuid) -> Result<(), TokenError> {
    git_access_token::Entity::delete_by_id(token_id)
        .exec(db)
        .await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::entity::{git_access_token, person};
    use crate::test_support::pg;
    use chrono::Duration;
    use sea_orm::ActiveModelTrait;

    async fn a_person(db: &Db) -> Uuid {
        person::ActiveModel {
            name: ActiveValue::Set("Libra".into()),
            email: ActiveValue::Set("libra@example.com".into()),
            ..Default::default()
        }
        .insert(db)
        .await
        .unwrap()
        .id
    }

    #[test]
    fn hash_is_stable_and_hex() {
        let h = hash_token("hunter2");
        assert_eq!(h.len(), 64);
        assert!(h.chars().all(|c| c.is_ascii_hexdigit()));
        assert_eq!(h, hash_token("hunter2"));
        assert_ne!(h, hash_token("hunter3"));
    }

    #[tokio::test]
    async fn mint_then_validate_resolves_identity_and_scope() {
        let db = pg().await;
        let person_id = a_person(&db).await;
        let now = Utc::now();

        let minted = mint(
            &db,
            person_id,
            None,
            git_access_token::SCOPE_WRITE,
            "the-plaintext-secret",
            now + Duration::hours(1),
        )
        .await
        .unwrap();

        // The plaintext is never stored — only its hash.
        assert_eq!(minted.token_hash, hash_token("the-plaintext-secret"));

        let resolved = validate(&db, "the-plaintext-secret", now)
            .await
            .unwrap()
            .expect("valid token resolves");
        assert_eq!(resolved.person_id, person_id);
        assert_eq!(resolved.scope, git_access_token::SCOPE_WRITE);
    }

    #[tokio::test]
    async fn unknown_token_does_not_validate() {
        let db = pg().await;
        let resolved = validate(&db, "never-minted", Utc::now()).await.unwrap();
        assert!(resolved.is_none());
    }

    #[tokio::test]
    async fn expired_token_is_treated_as_absent() {
        let db = pg().await;
        let person_id = a_person(&db).await;
        let now = Utc::now();

        mint(
            &db,
            person_id,
            None,
            git_access_token::SCOPE_READ,
            "already-expired",
            now - Duration::seconds(1),
        )
        .await
        .unwrap();

        let resolved = validate(&db, "already-expired", now).await.unwrap();
        assert!(resolved.is_none(), "an expired token must not validate");
    }

    #[tokio::test]
    async fn revoke_makes_a_token_stop_validating() {
        let db = pg().await;
        let person_id = a_person(&db).await;
        let now = Utc::now();

        let minted = mint(
            &db,
            person_id,
            None,
            git_access_token::SCOPE_READ,
            "revoke-me",
            now + Duration::hours(1),
        )
        .await
        .unwrap();

        assert!(validate(&db, "revoke-me", now).await.unwrap().is_some());
        revoke(&db, minted.id).await.unwrap();
        assert!(validate(&db, "revoke-me", now).await.unwrap().is_none());
    }
}
