import Foundation
import Yams

/// Reads Question.yaml and Jurisdiction.yaml from the given seeds directory and
/// writes a GeneratedSeeds.swift file to the output path.
///
/// Usage: GenerateSeedsExec <seeds-dir> <output-file>

guard CommandLine.arguments.count == 3 else {
    FileHandle.standardError.write(
        Data("Usage: GenerateSeedsExec <seeds-dir> <output-file>\n".utf8)
    )
    exit(1)
}

let seedsDir = CommandLine.arguments[1]
let outputPath = CommandLine.arguments[2]

// MARK: - YAML Parsing Helpers

/// Loads the records array from a seed YAML file.
func loadRecords(at path: String) throws -> [[String: Any]] {
    let raw = try String(contentsOfFile: path, encoding: .utf8)
    guard let top = try Yams.load(yaml: raw) as? [String: Any],
        let records = top["records"] as? [[String: Any]]
    else {
        return []
    }
    return records
}

/// Escapes a Swift string literal.
func escaped(_ value: String) -> String {
    value
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
}

// MARK: - Parse Questions

let questionPath = (seedsDir as NSString).appendingPathComponent("Question.yaml")
let questionRecords = try loadRecords(at: questionPath)

/// Deduplicate by code, keeping the last entry (mirrors how the DB seed lookup works).
var seenQuestionCodes: [String: (code: String, prompt: String)] = [:]
for record in questionRecords {
    guard let code = record["code"] as? String,
        let prompt = record["prompt"] as? String
    else { continue }
    seenQuestionCodes[code] = (code: code, prompt: prompt)
}
let questions = seenQuestionCodes.values.sorted { $0.code < $1.code }

// MARK: - Parse Jurisdictions

let jurisdictionPath = (seedsDir as NSString).appendingPathComponent("Jurisdiction.yaml")
let jurisdictionRecords = try loadRecords(at: jurisdictionPath)

struct JurisdictionEntry {
    let code: String
    let name: String
    let jurisdictionType: String
}

var jurisdictions: [JurisdictionEntry] = []
for record in jurisdictionRecords {
    guard let code = record["code"] as? String,
        let name = record["name"] as? String,
        let type_ = record["jurisdiction_type"] as? String
    else { continue }
    jurisdictions.append(JurisdictionEntry(code: code, name: name, jurisdictionType: type_))
}
jurisdictions.sort { $0.code < $1.code }

// MARK: - Generate Swift Source

var lines: [String] = []

lines.append("// Auto-generated by GenerateSeedsPlugin — do not edit directly.")
lines.append("// Source: Sources/NavigatorDAL/Seeds/Question.yaml, Jurisdiction.yaml")
lines.append("")
lines.append("/// A question record compiled from seed data at build time.")
lines.append("public struct QuestionSeed: Sendable {")
lines.append("    /// The unique code identifying this question type.")
lines.append("    public let code: String")
lines.append("    /// The human-readable prompt shown to respondents.")
lines.append("    public let prompt: String")
lines.append("}")
lines.append("")
lines.append("/// A jurisdiction record compiled from seed data at build time.")
lines.append("public struct JurisdictionSeed: Sendable {")
lines.append("    /// The short code for the jurisdiction (e.g. \"NV\", \"GMBH\").")
lines.append("    public let code: String")
lines.append("    /// The full name of the jurisdiction.")
lines.append("    public let name: String")
lines.append("    /// The jurisdiction type string (\"state\", \"country\", etc.).")
lines.append("    public let jurisdictionType: String")
lines.append("}")
lines.append("")
lines.append("/// Static seed data compiled from YAML source files at build time.")
lines.append("///")
lines.append("/// Use these values in place of loading seed data from the database,")
lines.append("/// which requires a bundle resource and crashes in binary installs.")
lines.append("public enum Seeds {")
lines.append("    /// All question seeds, sorted by code.")
lines.append("    public static let questions: [QuestionSeed] = [")
for q in questions {
    lines.append(
        "        QuestionSeed(code: \"\(escaped(q.code))\", prompt: \"\(escaped(q.prompt))\"),"
    )
}
lines.append("    ]")
lines.append("")
lines.append("    /// All jurisdiction seeds, sorted by code.")
lines.append("    public static let jurisdictions: [JurisdictionSeed] = [")
for j in jurisdictions {
    lines.append(
        "        JurisdictionSeed(code: \"\(escaped(j.code))\", name: \"\(escaped(j.name))\", jurisdictionType: \"\(escaped(j.jurisdictionType))\"),"
    )
}
lines.append("    ]")
lines.append("}")
lines.append("")

let output = lines.joined(separator: "\n")
try output.write(toFile: outputPath, atomically: true, encoding: .utf8)
